name: Change Request

on:
  workflow_dispatch:
    inputs:
      deploy_key:
        description: 'Enter the deployment key'
        required: true
        default: ''

jobs:
  validate_key:
    runs-on: ubuntu-latest
    outputs:
      validated: ${{ steps.set-output.outputs.validated }}
    steps:
      - name: Validate Key
        id: set-output
        run: |
          if [[ "${{ github.event.inputs.deploy_key }}" != "ash123" ]]; then
            echo " Invalid deployment key. Failing workflow."
            exit 1
          fi
          echo "Valid key"
          echo "validated=true" >> $GITHUB_OUTPUT

  build:
    needs: validate_key
    runs-on: ubuntu-latest
    if: needs.validate_key.outputs.validated == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build App
        run: echo " Building the application..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        run: echo " Deploying the application..."